### ISSUE TITLE
Lots of internal symbols exported

### ISSUE THREAD

**Issue by mcatanzaro** [Igalia/WPEBackend-fdo#103]
WPEBackend-fdo is exporting lots of symbols that are supposed to be internal. Anything beginning with Impl:: or WS::, for instance.

Adrian says: "We should switch to `-fvisibility=hidden` and explicitly mark public symbols." I agree.

Would make sense to make sure libwpe is in good shape too.

**Comment by aperezdc** [comment]
It turns out that public symbols are already marked with `__attribute__((visibility(default)))`, so this was very easy in the end.
