### ISSUE TITLE
ERROR: wpebackend-fdo-1.4.1-r0 do_compile

### ISSUE THREAD

**Issue by MehdiJaiem502** [Igalia/WPEBackend-fdo#133]
Hello 

While building a Yocto based image on my stm32 and running "bitbake st-image-weston ", the following compile error occurs.
**ERROR: wpebackend-fdo-1.4.1-r0 do_compile**

The whole error is `ERROR: wpebackend-fdo-1.4.1-r0 do_compile: Execution of '/opt/yocto/workspace/build-openstlinuxweston-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/wpebackend-fdo/1.4.1-r0/temp/run.do_compile.22007' failed with exit code 1:

:10: fatal error: EGL/eglmesaext.h: No such file or directory
|    30 | #include <EGL/eglmesaext.h>
|       |          ^~~~~~~~~~~~~~~~~~
| compilation terminated.
| ninja: build stopped: subcommand failed.

I don't know what to do and how to solve this. Does it have something to do with my local.conf file ?

thank you

**Comment by zdobersek** [comment]
Usage of that header was removed in 58c54c1f17d0d1373485329ca9824deb0d115ddc.

This change was then incorporated in the 1.4.2 release, so upgrading to that version in the 1.4 series should resolve the issue. General upgrade to newer release series would work too.
