### ISSUE TITLE
incompatibility with latest wayland protocol

### ISSUE THREAD

**Issue by limbo127** [Igalia/WPEBackend-fdo#173]
Hello, 
1784903.973] wl_output@11.scale(1)
[1784903.981] wl_output@11.name("eDP-1")
listener function for opcode 4 of wl_output is NULL
Aborted (core dumped)
it seems that is not compatible  with wl_output v4 and so was crashing when the latest wlroots
offered it.

Regards, 
Nicolas

**Comment by limbo127** [comment]
Hello,
Sorry it's two different case.
The first submit to cog is using weston, with virtio gpu.
This one is using sway, wlroots and cog or Minibrowser from wpewebkit.
Regards
Nicolas

Le lun. 4 avr. 2022 à 23:27, Adrian Perez ***@***.***> a
écrit :

**Comment by limbo127** [comment]
Sorry for my spam, I write from my phone without read your ref. Yes you have right, I close my issue.

**Comment by aperezdc** [comment]
@limbo127 No problem at all 👌🏼
