### ISSUE TITLE
Use “int” for file descritors everywhere

### ISSUE THREAD

**Issue by aperezdc** [Igalia/WPEBackend-fdo#56]
For example in the review of PR #55 we found out that there are some places where `int32_t` is being used for file descriptors, instead of `int` (which is the appropriate type).

**Comment by zdobersek** [comment]
We adopted int32_t (at least in linux_dmabuf_attributes) on our own:
https://github.com/Igalia/WPEBackend-fdo/pull/55#discussion_r301436658
https://gitlab.freedesktop.org/wayland/weston/blob/master/libweston/linux-dmabuf.h#L43

**Comment by aperezdc** [comment]
This has been fixed by PR #64, closing.
