### ISSUE TITLE
Support swrast configuration

### ISSUE THREAD

**Issue by zdobersek** [Igalia/WPEBackend-fdo#57]
Instead of wl_drm or dmabuf interfaces, it should be possible to run WPEBackend-fdo on top of swrast.

Specifically, this means providing the wl_shm interface inside the Wayland server that WPEBackend-fdo manages. Don't know if it's as simple as calling wl_display_init_shm() and letting Mesa take over everything else.

**Comment by philn** [comment]
This is done I guess?

**Comment by zdobersek** [comment]
Yes.
