### ISSUE TITLE
Add compiler warnings

### ISSUE THREAD

**Issue by mcatanzaro** [Igalia/WPEBackend-fdo#61]
WPEBackend-fdo should enable some compiler warnings. -Wall at minimum, and maybe also -Wextra.

**Comment by mcatanzaro** [comment]
I just noticed #58, that will fix this.

**Comment by aperezdc** [comment]
PR #58 has been merged, but we may want to look into adding `-Wextra`, or some other cherry-picked options not enabled by `-Wall`—we keep this issue open for that.

**Comment by mcatanzaro** [comment]
IMO -Wall is a good sane baseline set of warnings. Future issues can be created if more warnings are desired in the future.
