### ISSUE TITLE
Stopped building after changes to FindEGL.cmake

### ISSUE THREAD

**Issue by MichalKrasowski** [Igalia/WPEBackend-fdo#75]
The build fails with:
```
$ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig cmake .. -DCMAKE_BUILD_TYPE=Release
CMake Error at cmake/FindEGL.cmake:53 (target_link_libraries):
  Cannot specify link libraries for target "GL::egl" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:43 (find_package)


-- Configuring incomplete, errors occurred!
```

Reverting following commits fixes the problem.

fa6e47b95f3da3ae31971c84806ffcf8997d5fa6
943f85fa27da297c86f10307050fe9c790d417d0
ece5827693bf68c99555b3aa467b1f4dbfa63b74

**Comment by aperezdc** [comment]
@MichalKrasowski Hello! We want to use imported targets with CMake, but of course we don't want to break the build in those cases it was already working before. I am going to need some information about your build environment to investigate this:

- Which version of CMake are you using? The contents of the generated `CMakeCache.txt` and `CMakeFiles/CMakeOutput.log` files could be useful, too.
- Which package provides the EGL library and headers in your system? (for example, is it Mesa or is it a proprietary driver?)
- Is this a cross-compilation? If yes, are you using some build system like Buildroot or Yocto?

Thanks in advance for your time.

**Comment by aperezdc** [comment]
I have the suspicion that with CMake older than 3.3 we may need to use:

```cmake
target_link_libraries(<target> LINK_INTERFACE_LIBRARIES <libs...>)
```

instead of the current:

```cmake
target_link_libraries(<target> INTERFACE <libs...>)
```

I will still have to double-check this, this is just a wild guess looking at the differences in the CMake documentation for the 3.x releases.

**Comment by MichalKrasowski** [comment]
@aperezdc 
Thanks for a quick response, here are the details:

> Which version of CMake are you using? The contents of the generated CMakeCache.txt and CMakeFiles/CMakeOutput.log files could be useful, too.

```
cmake version 3.10.2
```

>Which package provides the EGL library and headers in your system? (for example, is it Mesa or is it a proprietary driver?)

I'm using `libegl1-mesa-dev` from my Ubuntu repository
```
apt version libegl1-mesa-dev 
19.0.8-0ubuntu0~18.04.1
```

(more inbound)

**Comment by aperezdc** [comment]
> @aperezdc
> Thanks for a quick response, here are the details:

Happy to help :construction_worker_man: 

> > Which version of CMake are you using? The contents of the generated CMakeCache.txt and CMakeFiles/CMakeOutput.log files could be useful, too.
> 
> ```
> cmake version 3.10.2
> ```
> 
> [CMakeCache.txt](https://github.com/Igalia/WPEBackend-fdo/files/3622011/CMakeCache.txt)
> [CMakeOutput.log](https://github.com/Igalia/WPEBackend-fdo/files/3622017/CMakeOutput.log)
> 
> > Which package provides the EGL library and headers in your system? (for example, is it Mesa or is it a proprietary driver?)
> 
> I'm using `libegl1-mesa-dev` from my Ubuntu repository
> 
> ```
> apt version libegl1-mesa-dev 
> 19.0.8-0ubuntu0~18.04.1
> ```

Great, thanks for all the info! I am going to spin up an Ubuntu `chroot` and try to reproduce the build issue, that should make it faster to figure out a fix.

**Comment by aperezdc** [comment]
At some point between CMake 3.10 and 3.14, it started being possible to use `target_link_libraries()` to add an imported target dependency to another imported target library target, but that was _not_ possible before. I have what I think is a relatively easy and reasonable fix, will open a MR soon.

**Comment by MichalKrasowski** [comment]
Fixed the problem. Thank you!

**Comment by aperezdc** [comment]
@MichalKrasowski Great, thanks for confirming that it's now working for you :ok_hand:
