### ISSUE TITLE
Does not handle Wayland compositor disappearing

### ISSUE THREAD

**Issue by TingPing** [Igalia/WPEBackend-fdo#84]
If the compositor exits the client process is just left running in the background, it should probably exit itself.

### Reproducer

```
weston --backend=x11-backend.so &
cog --platform=fdo

# Then close weston window
```

**Comment by tobias-grasse** [comment]
I've reported the same issue at https://github.com/Igalia/cog/issues/204 (with debug log and concrete scenario), but maybe better suited here.

**Comment by aperezdc** [comment]
Yes, I agree that this is indeed an issue to be solved Cog, so let's close the issue here.

@TingPing: If I understood your report wrong, please reopen and comment, or give me a ping by chat :smile_cat:
